# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accumulator_outer_cpp <- function(mat) {
    .Call(`_Dire_accumulator_outer_cpp`, mat)
}

accumulator_outer_fast <- function(mat) {
    .Call(`_Dire_accumulator_outer_fast`, mat)
}

ldbinomC <- function(x, pr) {
    .Call(`_Dire_ldbinomC`, x, pr)
}

multItems <- function(x1, guess, D, slope, nodes, difficulty) {
    .Call(`_Dire_multItems`, x1, guess, D, slope, nodes, difficulty)
}

