# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsum1 <- function(x) {
    .Call(`_Dire_cumsum1`, x)
}

GPCMC <- function(d, a, theta, score, D) {
    .Call(`_Dire_GPCMC`, d, a, theta, score, D)
}

polyLvls <- function(d, a, theta, score, D) {
    .Call(`_Dire_polyLvls`, d, a, theta, score, D)
}

ansItems <- function(d, a, theta, score, D) {
    .Call(`_Dire_ansItems`, d, a, theta, score, D)
}

ldbinomC <- function(x, pr) {
    .Call(`_Dire_ldbinomC`, x, pr)
}

multItems <- function(x1, guess, D, slope, nodes, difficulty) {
    .Call(`_Dire_multItems`, x1, guess, D, slope, nodes, difficulty)
}

grSum2 <- function(w, trr2mxb, X_, xi, s2, denom) {
    .Call(`_Dire_grSum2`, w, trr2mxb, X_, xi, s2, denom)
}

matTimesVec <- function(mat, v) {
    .Call(`_Dire_matTimesVec`, mat, v)
}

calcHess <- function(K, rr2, rr2_, trr2mxb, X_, nodesminusXB, w, s2, s_) {
    .Call(`_Dire_calcHess`, K, rr2, rr2_, trr2mxb, X_, nodesminusXB, w, s2, s_)
}

calcHessOld <- function(K, rr2, rr2_, trr2mxb, X_, nodesminusXB, w, s2, s_) {
    .Call(`_Dire_calcHessOld`, K, rr2, rr2_, trr2mxb, X_, nodesminusXB, w, s2, s_)
}

calcRrij <- function(i, j, rr1fi, rr2fj, detSigma, mvnResid) {
    .Call(`_Dire_calcRrij`, i, j, rr1fi, rr2fj, detSigma, mvnResid)
}

