# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumsum1 <- function(x) {
    .Call(`_Dire_cumsum1`, x)
}

GPCM <- function(d, a, theta, score, D) {
    .Call(`_Dire_GPCM`, d, a, theta, score, D)
}

polyLvls <- function(d, a, theta, score, D) {
    .Call(`_Dire_polyLvls`, d, a, theta, score, D)
}

ansItems <- function(d, a, theta, score, D) {
    .Call(`_Dire_ansItems`, d, a, theta, score, D)
}

ldbinom2 <- function(x, pr) {
    .Call(`_Dire_ldbinom2`, x, pr)
}

multItems <- function(x1, guess, D, slope, nodes, difficulty) {
    .Call(`_Dire_multItems`, x1, guess, D, slope, nodes, difficulty)
}

calcRrij <- function(i, j, rr1fi, rr2fj, detSigma, mvnResid) {
    .Call(`_Dire_calcRrij`, i, j, rr1fi, rr2fj, detSigma, mvnResid)
}

